services:
  - type: web
    name: engacademy-backend
    runtime: docker
    dockerfilePath: Dockerfile
    region: singapore
    healthCheckPath: /api/v1/auth/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: APPLICATION_SECURITY_JWT_SECRET_KEY
        generateValue: true
      - key: APPLICATION_SECURITY_JWT_EXPIRATION
        value: 86400000
      - key: APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION
        value: 604800000
      - key: APPLICATION_CORS_ALLOWED_ORIGINS
        value: http://eng-academy-lms.vercel.app,https://eng-academy-admin.vercel.app
      - key: SPRING_DATA_REDIS_HOST
        value: renewed-tadpole-87254.upstash.io
      - key: SPRING_DATA_REDIS_PORT
        value: 6379
      - key: SPRING_DATA_REDIS_USERNAME
        value: default
      - key: SPRING_DATA_REDIS_PASSWORD
        sync: false
      - key: SPRING_DATA_REDIS_SSL
        value: true
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://hopper.proxy.rlwy.net:56199/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: 587
      - key: SPRING_MAIL_USERNAME
        value: dinhminh4424@gmail.com
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: RATE_LIMIT_MAX_ATTEMPTS
        value: 100
      - key: RATE_LIMIT_WINDOW_SECONDS
        value: 60
      - key: RATE_LIMIT_ENABLED
        value: true
