const fs = require('fs');
const path = require('path');

class CustomReporter {
    constructor(globalConfig, options) {
        this._globalConfig = globalConfig;
        this._options = options;
    }

    onRunComplete(testContexts, results) {
        let html = `<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E2E Test Report</title>
    <style>
        :root {
            --primary: #4f46e5;
            --success: #10b981;
            --danger: #ef4444;
            --warning: #f59e0b;
            --bg: #f3f4f6;
            --border: #e5e7eb;
            --text-main: #1f2937;
            --text-muted: #6b7280;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: var(--bg); color: var(--text-main); padding: 30px; }
        .container { max-width: 1400px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05); overflow: hidden; }
        .header { background: #1e1b4b; color: white; padding: 25px 30px; display: flex; justify-content: space-between; align-items: center; }
        .header h1 { font-size: 24px; font-weight: 600; margin: 0; }
        .summary-cards { display: flex; gap: 20px; padding: 25px 30px; background: #fafafa; border-bottom: 1px solid var(--border); }
        .card { flex: 1; background: white; border: 1px solid var(--border); border-radius: 8px; padding: 20px; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
        .card-value { font-size: 32px; font-weight: 700; margin-bottom: 5px; }
        .card-label { font-size: 13px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.5px; font-weight: 600; }
        .c-total .card-value { color: var(--primary); }
        .c-pass .card-value { color: var(--success); }
        .c-fail .card-value { color: var(--danger); }
        .table-wrapper { padding: 30px; overflow-x: auto; }
        table { width: 100%; border-collapse: collapse; font-size: 14px; }
        th, td { padding: 14px 16px; text-align: left; border-bottom: 1px solid var(--border); line-height: 1.5; }
        th { background: #312e81; color: white; font-weight: 600; text-transform: uppercase; font-size: 12px; letter-spacing: 0.5px; white-space: nowrap; position: sticky; top: 0; }
        tr:hover td { background-color: #f8fafc; }
        .id-badge { display: inline-block; background: #e0e7ff; color: #3730a3; padding: 4px 8px; border-radius: 4px; font-weight: 600; font-family: monospace; font-size: 13px; white-space: nowrap; }
        .badge { display: inline-block; padding: 5px 10px; border-radius: 20px; font-weight: 600; font-size: 12px; text-align: center; min-width: 80px; }
        .badge-passed { background: #d1fae5; color: #065f46; }
        .badge-failed { background: #fee2e2; color: #991b1b; }
        .action-link { display: inline-block; background: var(--primary); color: white; text-decoration: none; padding: 6px 12px; border-radius: 6px; font-size: 12px; font-weight: 500; transition: background 0.2s; white-space: nowrap; }
        .action-link:hover { background: #4338ca; }
        .action-none { color: var(--text-muted); font-size: 13px; font-style: italic; }
        .desc-col { max-width: 300px; }
        .subitem-col { color: #4338ca; font-weight: 500; font-size: 13px; }
        .expected-col { font-size: 13px; color: var(--text-muted); }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Automated E2E Test Report</h1>
            <div style="font-size: 14px; opacity: 0.8">Generated by Custom Jest Reporter</div>
        </div>
        <div class="summary-cards">
            <div class="card c-total">
                <div class="card-value">${results.numTotalTests}</div>
                <div class="card-label">Total Tests</div>
            </div>
            <div class="card c-pass">
                <div class="card-value">${results.numPassedTests}</div>
                <div class="card-label">Passed</div>
            </div>
            <div class="card c-fail">
                <div class="card-value">${results.numFailedTests}</div>
                <div class="card-label">Failed</div>
            </div>
        </div>
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th width="8%">ID</th>
                        <th width="12%">Items</th>
                        <th width="15%">Sub-items</th>
                        <th width="22%">Description</th>
                        <th width="8%">Exec time</th>
                        <th width="15%">Expected Output</th>
                        <th width="10%">Status</th>
                        <th width="10%">Action</th>
                    </tr>
                </thead>
                <tbody>
`;

        results.testResults.forEach(suite => {
            suite.testResults.forEach(test => {
                const item = test.ancestorTitles[0] || 'E2E Testing';
                const subItemRaw = test.ancestorTitles[1] || '';
                const subItem = subItemRaw.replace(/PHẦN \d+:\s*/, '');
                
                let id = 'TC-E2E';
                let description = test.title;
                
                const match1 = test.title.match(/^([^:]+):\s*(.*)$/);
                const match2 = test.title.match(/^(\d+)\.\s*(.*)$/);
                
                if (match1) {
                    id = match1[1];
                    description = match1[2];
                } else if (match2) {
                    id = `TC-${match2[1].padStart(2, '0')}`;
                    description = match2[2];
                }

                const execTime = test.duration ? test.duration + ' ms' : '< 1 ms';
                const isPassed = test.status === 'passed';
                const statusHtml = isPassed 
                    ? '<span class="badge badge-passed">Passed</span>' 
                    : '<span class="badge badge-failed">Failed</span>';
                
                let expectedOutput = isPassed ? 'Passes all assertions without throwing exceptions.' : 'Process completed successfully.';
                if (description.toLowerCase().includes('đăng nhập thành công')) expectedOutput = 'Redirect to dashboard, name displayed.';
                else if (description.toLowerCase().includes('sai mật khẩu')) expectedOutput = 'Display error message, stay on login.';
                
                const testNameSafe = test.title.replace(/[^a-zA-Z0-9]/g, '_');
                const screenshotFile = testNameSafe + '.png';
                
                let actionHtml = `<a href="../Screenshots/${screenshotFile}" target="_blank" class="action-link">View Screenshot</a>`;

                html += `
                    <tr>
                        <td><span class="id-badge">${id}</span></td>
                        <td style="font-weight: 500; font-size: 13px;">${item.replace(/KỊCH BẢN KIỂM THỬ E2E TOÀN DIỆN.*/, 'Toàn bộ E2E')}</td>
                        <td class="subitem-col">${subItem}</td>
                        <td class="desc-col">${description}</td>
                        <td style="font-family: monospace; font-size: 13px;">${execTime}</td>
                        <td class="expected-col">${expectedOutput}</td>
                        <td>${statusHtml}</td>
                        <td>${actionHtml}</td>
                    </tr>`;
            });
        });

        html += `
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>`;

        const reportDir = path.join(__dirname, 'Reports');
        if (!fs.existsSync(reportDir)) {
            fs.mkdirSync(reportDir, { recursive: true });
        }
        
        const reportPath = path.join(reportDir, 'test-report.html');
        fs.writeFileSync(reportPath, html, 'utf8');
        console.log('\n✅ [CustomReporter] Created custom HTML report at: ' + reportPath + '\n');
    }
}

module.exports = CustomReporter;
